# Generated by Django 6.0.5 on 2026-06-02 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=22, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=22, null=True)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('parent_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='Branches.branch')),
            ],
        ),
    ]
