# Generated by Django 6.0.5 on 2026-06-02 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=22, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('home_address', models.CharField()),
                ('parent_nuber', models.CharField(max_length=22)),
                ('status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('dropped', 'Dropped')], default='active', max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='Branches.branch')),
            ],
        ),
    ]
