# Generated by Django 6.0.5 on 2026-05-18 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Branches', '0001_initial'),
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('CLOSED', 'closed')], default='ACTIVE', max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group', to='Branches.branch')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group', to='Students.student')),
            ],
        ),
    ]
