# Generated by Django 6.0.5 on 2026-06-02 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Groups', '0001_initial'),
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='Students.student'),
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(related_name='groups', through='Groups.GroupMembership', to='Students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'student')},
        ),
    ]
