# Generated by Django 6.0.5 on 2026-05-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branches', '0004_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.CharField(default='lviv', max_length=255),
            preserve_default=False,
        ),
    ]
