# Generated by Django 6.0.5 on 2026-05-29 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branches', '0002_alter_subject_name_and_more'),
        ('Users', '0003_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Branches.branch'),
        ),
    ]
