# Generated by Django 6.0.5 on 2026-05-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branches', '0002_alter_subject_name_and_more'),
        ('Users', '0004_customuser_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='branch',
        ),
        migrations.AddField(
            model_name='customuser',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='users', to='Branches.branch'),
        ),
    ]
