# Generated by Django 6.0.5 on 2026-05-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branches', '0002_alter_subject_name_and_more'),
        ('Users', '0005_remove_customuser_branch_customuser_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='branch', to='Branches.branch'),
        ),
    ]
