# Generated by Django 6.0.5 on 2026-05-19 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branches', '0002_alter_subject_name_and_more'),
        ('Students', '0001_initial'),
        ('Subscriptions', '0002_plan_prise_trail_student_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_subscription',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student_subscription',
            name='subscription_plan',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_plans', to='Branches.branch'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=20),
        ),
        migrations.CreateModel(
            name='PlanPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_lesson', models.IntegerField()),
                ('lessons_per_month', models.IntegerField()),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='Subscriptions.subscriptionplan')),
            ],
            options={
                'unique_together': {('subscription_plan', 'lessons_per_month')},
            },
        ),
        migrations.CreateModel(
            name='StudentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('plan_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_subscriptions', to='Subscriptions.planpricetier')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='Students.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Plan_prise_trail',
        ),
        migrations.DeleteModel(
            name='Student_subscription',
        ),
    ]
